name = "deepseek-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量（通过 wrangler secret 或 Cloudflare 控制台设置）
# DEEPSEEK_API_KEY = "your-deepseek-api-key"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }